unstable_features = true

version = "Two"

group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
reorder_imports = true

use_small_heuristics = "Max"

wrap_comments = true

reorder_impl_items = true
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
use_field_init_shorthand = true

format_strings = true
format_code_in_doc_comments = true
format_macro_matchers = true

ignore = [
    "cierra/src/parser/taurus"
]